### ISSUE TITLE
Cannot import Module

### ISSUE THREAD

**Issue by RafaelWO** [mellesies/cmh#1]
I installed the package via PyPI: `pip install CMH`

When trying to import `CMH` as shown in the README I get an error:

```
>>> from cmh import CMH
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/torch/lib/python3.8/site-packages/cmh/__init__.py", line 10, in <module>
    from ._version import __version__  # noqa
  File "/home/user/miniconda3/envs/torch/lib/python3.8/site-packages/cmh/_version.py", line 6, in <module>
    with open(os.path.join(here, '__build__')) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/miniconda3/envs/torch/lib/python3.8/site-packages/cmh/__build__'
```

Any ideas?

**Comment by RafaelWO** [comment]
It works when installing from source:
```
git clone https://github.com/mellesies/cmh.git
cd cmd
pip install -e .
```
